apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-deployment
  labels:
    app: todo-api
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        env:
        - name: DATABASE_URL
          value: "postgresql+psycopg2://todo:changeme@todo-db-postgresql:5432/todo-db"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 5